version: 1

labels:
  # Type labels
  - label: "type: bug"
    title: '^:bug:.*'
  - label: "type: feature"
    title: '^(:sparkles:|:tada:|:art:).*'
  - label: "type: improvement"
    title: '^(:\\+1:|:recycle:|:rocket:).*'
  - label: "type: docs"
    title: '^:books:.*'
    files:
      - "docs/.+"
      - "**/README\\.md"
  - label: "type: version"
    title: '^:up:.*'
    files:
      - "**/pubspec\\.yaml"
      - "**/melos\\.yaml"
  - label: "type: tool"
    title: '^:wrench:.*'
    files:
      - '\\.github/.+'
      - 'tools/.+'

  # Core Package labels
  - label: "core: network"
    files:
      - "packages/core/network/.+"
  - label: "core: database"
    files:
      - "packages/core/database/.+"
  - label: "core: datastore"
    files:
      - "packages/core/datastore/.+"
  - label: "core: data"
    files:
      - "packages/core/data/.+"
  - label: "core: model"
    files:
      - "packages/core/model/.+"
  - label: "core: domain"
    files:
      - "packages/core/domain/.+"
  - label: "core: testing"
    files:
      - "packages/core/testing/.+"
  - label: "core: ui"
    files:
      - "packages/core/ui/.+"
  - label: "core: design"
    files:
      - "packages/core/design/.+"
  - label: "core: common"
    files:
      - "packages/core/common/.+"

  # Feature Package labels
  # TBD

  # Apps labels
  # TBD