# When you use this template, you must change this name field.
name: flutter_template

sdkPath: .fvm/flutter_sdk

packages:
  - app
  - core/*
  - feature/*

# if you use intellij, you can use this setting.
#ide:
#  intellij:
#    moduleNamePrefix: [yourProjectName]_

command:
  bootstrap:
    environment:
      sdk: 3.2.4
      flutter: 3.16.7
    dev_dependencies:
      test: 1.24.0
      yumemi_lints: 1.4.0

scripts:
  analyze:
    run: |
      melos exec -- "dart analyze"
    description: Run analyze.
    packageFilters:
      dirExists: lib

  gen:code:
    run: |
      melos exec -c 1 -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run build_runner.
    packageFilters:
      dependsOn: "build_runner"
  gen:l10n:
    run: |
      melos exec -c 1 -- "flutter gen-l10n"
    description: Generate l10n.
    packageFilters:
      flutter: true
      fileExists: "l10n.yaml"

  fix:
    run: |
      melos exec -- "dart fix --apply lib"
    description: Run dart fix.
    packageFilters:
      dirExists: lib
  fix:check:
    run: |
      melos exec -- "dart fix --dry-run lib"
    description: Check dart fix.
    packageFilters:
      dirExists: lib

  format:
    run: |
      melos exec -- "dart format lib"
    description: Run format.
    packageFilters:
      dirExists: lib
  format:check:
    run: |
      melos exec -- "dart format lib --dry-run --set-exit-if-changed"
    description: Check format.
    packageFilters:
      dirExists: lib

  test:dart:
    run: |
      melos exec -c 10 --fail-fast -- dart test --coverage
    description: Run dart test.
    packageFilters:
      dirExists: test
      dependsOn: "test"
  test:flutter:
    run: |
      melos exec -c 10 --fail-fast -- flutter test --coverage
    description: Run flutter test.
    packageFilters:
      flutter: true
      dirExists: test
      dependsOn: "flutter_test"
