# When you use this template, you must change this name field.
name: flutter_template

environment:
  sdk: 3.2.4
dev_dependencies:
  melos: 4.0.0
  yumemi_lints:
    git: https://github.com/yumemi-inc/flutter-yumemi-lints.git
