name: core_designsystem
description: This package provides style definitions, themes, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: 2.2.0

flutter:
