name: core_designsystem
description: This package provides style definitions, themes, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.2.4
  flutter: 3.16.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints:
    git: https://github.com/yumemi-inc/flutter-yumemi-lints.git

flutter:
