name: core_designsystem
description: This package provides style definitions, themes, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.3.1
  flutter: 3.19.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: 1.7.0

flutter:
