name: core_ui
description: This package provides a UI that depends on the model class and is used by all packages.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.3.0
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: 1.6.0

flutter:
