name: core_ui
description: This package provides a UI that depends on the model class and is used by all packages.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.7.1
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: 1.7.0

flutter:
