name: core_datastore
description: This package provides local preferences operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.2.4

dependencies:

dev_dependencies:
  test: 1.24.0
  yumemi_lints:
    git: https://github.com/yumemi-inc/flutter-yumemi-lints.git
