name: core_datastore
description: This package provides local preferences operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.3.0

dependencies:

dev_dependencies:
  test: 1.25.2
  yumemi_lints: 1.7.0
