name: core_domain
description: This package provides use cases and domain models.
publish_to: "none"

environment:
  sdk: 3.2.4

dependencies:

dev_dependencies:
  test: 1.24.0
  yumemi_lints:
    git: https://github.com/yumemi-inc/flutter-yumemi-lints.git
