# https://github.com/azu/github-label-setup
name: Setup Labels
on:
  workflow_dispatch:
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn add -D @azu/github-label-setup
      - name: update label
        run: yarn github-label-setup --token ${{ secrets.PERSONAL_ACCESS_TOKEN }} --labels .github/labels.json